// <auto-generated />
using System;
using ElegiBien.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElegiBien.Infrastructure.Migrations
{
    [DbContext(typeof(ElegiBienDbContext))]
    partial class ElegiBienDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElegiBien.Domain.Entities.AirConditioningInput", b =>
                {
                    b.Property<Guid>("AirConditioningInputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClimateZone")
                        .HasColumnType("int");

                    b.Property<bool>("HasHighHeatEquipment")
                        .HasColumnType("bit");

                    b.Property<decimal>("HeightMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("InsulationLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsHeightAssumed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpenToAnotherSpace")
                        .HasColumnType("bit");

                    b.Property<decimal>("LengthMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<int>("SunExposure")
                        .HasColumnType("int");

                    b.Property<decimal>("WidthMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("WindowExposure")
                        .HasColumnType("int");

                    b.HasKey("AirConditioningInputId");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("AirConditioningInputs", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.Analysis", b =>
                {
                    b.Property<Guid>("AnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("MethodologyVersionId")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.HasKey("AnalysisId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("MethodologyVersionId");

                    b.HasIndex("CategoryId", "CreatedAtUtc");

                    b.ToTable("Analyses", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.AnalyticsEvent", b =>
                {
                    b.Property<Guid>("AnalyticsEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<int?>("Mode")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("AnalyticsEventId");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("CategoryId", "OccurredAtUtc");

                    b.HasIndex("EventType", "OccurredAtUtc");

                    b.ToTable("AnalyticsEvents", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ComparisonAlternative", b =>
                {
                    b.Property<Guid>("ComparisonAlternativeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryCode")
                        .HasColumnType("int");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ComparisonAlternativeId");

                    b.HasIndex("CategoryCode");

                    b.HasIndex("AnalysisId", "Position")
                        .IsUnique();

                    b.ToTable("ComparisonAlternatives", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ComparisonFactor", b =>
                {
                    b.Property<Guid>("ComparisonFactorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComparisonScoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FactorCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("MaximumScore")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Score")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.HasKey("ComparisonFactorId");

                    b.HasIndex("ComparisonScoreId", "FactorCode")
                        .IsUnique();

                    b.ToTable("ComparisonFactors", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ComparisonScore", b =>
                {
                    b.Property<Guid>("ComparisonScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AppliedMaximumScore")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("ComparisonAlternativeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("bit");

                    b.Property<string>("StatusCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("ComparisonScoreId");

                    b.HasIndex("ComparisonAlternativeId")
                        .IsUnique();

                    b.ToTable("ComparisonScores", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ConsentRecord", b =>
                {
                    b.Property<Guid>("ConsentRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConsentType")
                        .HasColumnType("int");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("bit");

                    b.Property<string>("LegalVersion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ConsentRecordId");

                    b.HasIndex("RecordedAtUtc");

                    b.HasIndex("AnalysisId", "ConsentType");

                    b.ToTable("ConsentRecords", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.DimensioningResult", b =>
                {
                    b.Property<Guid>("DimensioningResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdjustmentFrigories")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseFrigories")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedFrigories")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("IdealFrigories")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("RecommendedMaximumFrigories")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("RecommendedMinimumFrigories")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("RequiresProfessionalReview")
                        .HasColumnType("bit");

                    b.Property<decimal>("VolumeCubicMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("DimensioningResultId");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("DimensioningResults", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.FlooringCalculationResult", b =>
                {
                    b.Property<Guid>("FlooringCalculationResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("RequiredAreaSquareMeters")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("RequiresProfessionalReview")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalAreaSquareMeters")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("WasteAreaSquareMeters")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("WastePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("FlooringCalculationResultId");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("FlooringCalculationResults", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.FlooringInput", b =>
                {
                    b.Property<Guid>("FlooringInputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InstallationPattern")
                        .HasColumnType("int");

                    b.Property<decimal>("LengthMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("WastePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("WidthMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("FlooringInputId");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("FlooringInputs", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.HeatingCalculationResult", b =>
                {
                    b.Property<Guid>("HeatingCalculationResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdjustmentPowerWatts")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePowerWatts")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedPowerWatts")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("IdealPowerKcalPerHour")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("IdealPowerWatts")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("RecommendedMaximumWatts")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("RecommendedMinimumWatts")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("RequiresProfessionalReview")
                        .HasColumnType("bit");

                    b.Property<decimal>("SurfaceSquareMeters")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("VolumeCubicMeters")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("HeatingCalculationResultId");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("HeatingCalculationResults", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.HeatingInput", b =>
                {
                    b.Property<Guid>("HeatingInputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClimateZone")
                        .HasColumnType("int");

                    b.Property<int>("ExteriorWallsCount")
                        .HasColumnType("int");

                    b.Property<decimal>("HeightMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("InsulationLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsHeightAssumed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpenToAnotherSpace")
                        .HasColumnType("bit");

                    b.Property<decimal>("LengthMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("WidthMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("WindowExposure")
                        .HasColumnType("int");

                    b.HasKey("HeatingInputId");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("HeatingInputs", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.MethodologyVersion", b =>
                {
                    b.Property<int>("MethodologyVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MethodologyVersionId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MethodologyVersionId");

                    b.HasIndex("CategoryId", "Version")
                        .IsUnique();

                    b.ToTable("MethodologyVersions", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.PaintCalculationResult", b =>
                {
                    b.Property<Guid>("PaintCalculationResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdjustedAreaSquareMeters")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CeilingAreaSquareMeters")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("DeductedAreaSquareMeters")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("NetAreaSquareMeters")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ReferenceCoverageSquareMetersPerLiter")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("ReferenceLiters")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("RequiresProfessionalReview")
                        .HasColumnType("bit");

                    b.Property<decimal>("WallAreaSquareMeters")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("PaintCalculationResultId");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("PaintCalculationResults", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.PaintInput", b =>
                {
                    b.Property<Guid>("PaintInputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CoatCount")
                        .HasColumnType("int");

                    b.Property<int>("DoorCount")
                        .HasColumnType("int");

                    b.Property<decimal>("HeightMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<bool>("IncludeCeiling")
                        .HasColumnType("bit");

                    b.Property<decimal>("LengthMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("SurfaceCondition")
                        .HasColumnType("int");

                    b.Property<decimal>("WastePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("WidthMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("WindowCount")
                        .HasColumnType("int");

                    b.HasKey("PaintInputId");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("PaintInputs", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.SharedResult", b =>
                {
                    b.Property<Guid>("SharedResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessCount")
                        .HasColumnType("int");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAccessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublicToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SharedResultId");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.HasIndex("PublicToken")
                        .IsUnique();

                    b.HasIndex("IsActive", "ExpiresAtUtc");

                    b.ToTable("SharedResults", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.AirConditioningInput", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Analysis", "Analysis")
                        .WithOne("AirConditioningInput")
                        .HasForeignKey("ElegiBien.Domain.Entities.AirConditioningInput", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.Analysis", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElegiBien.Domain.Entities.MethodologyVersion", "MethodologyVersion")
                        .WithMany()
                        .HasForeignKey("MethodologyVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("MethodologyVersion");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.AnalyticsEvent", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Analysis", "Analysis")
                        .WithMany("AnalyticsEvents")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ElegiBien.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Analysis");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ComparisonAlternative", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Analysis", "Analysis")
                        .WithMany("ComparisonAlternatives")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ComparisonFactor", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.ComparisonScore", "ComparisonScore")
                        .WithMany("Factors")
                        .HasForeignKey("ComparisonScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComparisonScore");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ComparisonScore", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.ComparisonAlternative", "Alternative")
                        .WithOne("Score")
                        .HasForeignKey("ElegiBien.Domain.Entities.ComparisonScore", "ComparisonAlternativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alternative");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ConsentRecord", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Analysis", "Analysis")
                        .WithMany("ConsentRecords")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.DimensioningResult", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Analysis", "Analysis")
                        .WithOne("DimensioningResult")
                        .HasForeignKey("ElegiBien.Domain.Entities.DimensioningResult", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.FlooringCalculationResult", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Analysis", "Analysis")
                        .WithOne("FlooringCalculationResult")
                        .HasForeignKey("ElegiBien.Domain.Entities.FlooringCalculationResult", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.FlooringInput", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Analysis", "Analysis")
                        .WithOne("FlooringInput")
                        .HasForeignKey("ElegiBien.Domain.Entities.FlooringInput", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.HeatingCalculationResult", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Analysis", "Analysis")
                        .WithOne("HeatingCalculationResult")
                        .HasForeignKey("ElegiBien.Domain.Entities.HeatingCalculationResult", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.HeatingInput", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Analysis", "Analysis")
                        .WithOne("HeatingInput")
                        .HasForeignKey("ElegiBien.Domain.Entities.HeatingInput", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.MethodologyVersion", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.PaintCalculationResult", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Analysis", "Analysis")
                        .WithOne("PaintCalculationResult")
                        .HasForeignKey("ElegiBien.Domain.Entities.PaintCalculationResult", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.PaintInput", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Analysis", "Analysis")
                        .WithOne("PaintInput")
                        .HasForeignKey("ElegiBien.Domain.Entities.PaintInput", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.SharedResult", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Analysis", "Analysis")
                        .WithOne("SharedResult")
                        .HasForeignKey("ElegiBien.Domain.Entities.SharedResult", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.Analysis", b =>
                {
                    b.Navigation("AirConditioningInput");

                    b.Navigation("AnalyticsEvents");

                    b.Navigation("ComparisonAlternatives");

                    b.Navigation("ConsentRecords");

                    b.Navigation("DimensioningResult");

                    b.Navigation("FlooringCalculationResult");

                    b.Navigation("FlooringInput");

                    b.Navigation("HeatingCalculationResult");

                    b.Navigation("HeatingInput");

                    b.Navigation("PaintCalculationResult");

                    b.Navigation("PaintInput");

                    b.Navigation("SharedResult");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ComparisonAlternative", b =>
                {
                    b.Navigation("Score");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ComparisonScore", b =>
                {
                    b.Navigation("Factors");
                });
#pragma warning restore 612, 618
        }
    }
}
