// <auto-generated />
using System;
using ElegiBien.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElegiBien.Infrastructure.Migrations
{
    [DbContext(typeof(ElegiBienDbContext))]
    partial class ElegiBienDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElegiBien.Domain.Entities.AirConditioningInput", b =>
                {
                    b.Property<Guid>("AirConditioningInputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClimateZone")
                        .HasColumnType("int");

                    b.Property<bool>("HasHighHeatEquipment")
                        .HasColumnType("bit");

                    b.Property<decimal>("HeightMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("InsulationLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsHeightAssumed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpenToAnotherSpace")
                        .HasColumnType("bit");

                    b.Property<decimal>("LengthMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<int>("SunExposure")
                        .HasColumnType("int");

                    b.Property<decimal>("WidthMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("WindowExposure")
                        .HasColumnType("int");

                    b.HasKey("AirConditioningInputId");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("AirConditioningInputs", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.Analysis", b =>
                {
                    b.Property<Guid>("AnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("MethodologyVersionId")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.HasKey("AnalysisId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("MethodologyVersionId");

                    b.HasIndex("CategoryId", "CreatedAtUtc");

                    b.ToTable("Analyses", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.AnalyticsEvent", b =>
                {
                    b.Property<Guid>("AnalyticsEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<int?>("Mode")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("AnalyticsEventId");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("CategoryId", "OccurredAtUtc");

                    b.HasIndex("EventType", "OccurredAtUtc");

                    b.ToTable("AnalyticsEvents", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ConsentRecord", b =>
                {
                    b.Property<Guid>("ConsentRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConsentType")
                        .HasColumnType("int");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("bit");

                    b.Property<string>("LegalVersion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ConsentRecordId");

                    b.HasIndex("RecordedAtUtc");

                    b.HasIndex("AnalysisId", "ConsentType");

                    b.ToTable("ConsentRecords", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.DimensioningResult", b =>
                {
                    b.Property<Guid>("DimensioningResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdjustmentFrigories")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseFrigories")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedFrigories")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("IdealFrigories")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("RecommendedMaximumFrigories")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("RecommendedMinimumFrigories")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("RequiresProfessionalReview")
                        .HasColumnType("bit");

                    b.Property<decimal>("VolumeCubicMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("DimensioningResultId");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("DimensioningResults", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.MethodologyVersion", b =>
                {
                    b.Property<int>("MethodologyVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MethodologyVersionId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MethodologyVersionId");

                    b.HasIndex("CategoryId", "Version")
                        .IsUnique();

                    b.ToTable("MethodologyVersions", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ProductAlternative", b =>
                {
                    b.Property<Guid>("ProductAlternativeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("CapacityFrigories")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("NominalConsumptionWatts")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReferenceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Technology")
                        .HasColumnType("int");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("int");

                    b.HasKey("ProductAlternativeId");

                    b.HasIndex("AnalysisId");

                    b.ToTable("ProductAlternatives", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ProductScore", b =>
                {
                    b.Property<Guid>("ProductScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AppliedMaximumScore")
                        .HasColumnType("int");

                    b.Property<int>("CapacityStatus")
                        .HasColumnType("int");

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductAlternativeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.HasKey("ProductScoreId");

                    b.HasIndex("ProductAlternativeId")
                        .IsUnique();

                    b.ToTable("ProductScores", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ScoreFactor", b =>
                {
                    b.Property<Guid>("ScoreFactorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FactorType")
                        .HasColumnType("int");

                    b.Property<decimal>("MaximumScore")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid>("ProductScoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Score")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ScoreFactorId");

                    b.HasIndex("ProductScoreId");

                    b.ToTable("ScoreFactors", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.SharedResult", b =>
                {
                    b.Property<Guid>("SharedResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessCount")
                        .HasColumnType("int");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAccessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublicToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SharedResultId");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.HasIndex("PublicToken")
                        .IsUnique();

                    b.HasIndex("IsActive", "ExpiresAtUtc");

                    b.ToTable("SharedResults", (string)null);
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.AirConditioningInput", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Analysis", "Analysis")
                        .WithOne("AirConditioningInput")
                        .HasForeignKey("ElegiBien.Domain.Entities.AirConditioningInput", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.Analysis", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElegiBien.Domain.Entities.MethodologyVersion", "MethodologyVersion")
                        .WithMany()
                        .HasForeignKey("MethodologyVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("MethodologyVersion");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.AnalyticsEvent", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Analysis", "Analysis")
                        .WithMany("AnalyticsEvents")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ElegiBien.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Analysis");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ConsentRecord", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Analysis", "Analysis")
                        .WithMany("ConsentRecords")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.DimensioningResult", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Analysis", "Analysis")
                        .WithOne("DimensioningResult")
                        .HasForeignKey("ElegiBien.Domain.Entities.DimensioningResult", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.MethodologyVersion", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ProductAlternative", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Analysis", "Analysis")
                        .WithMany("ProductAlternatives")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ProductScore", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.ProductAlternative", "ProductAlternative")
                        .WithOne("ProductScore")
                        .HasForeignKey("ElegiBien.Domain.Entities.ProductScore", "ProductAlternativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductAlternative");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ScoreFactor", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.ProductScore", "ProductScore")
                        .WithMany("Factors")
                        .HasForeignKey("ProductScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductScore");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.SharedResult", b =>
                {
                    b.HasOne("ElegiBien.Domain.Entities.Analysis", "Analysis")
                        .WithOne("SharedResult")
                        .HasForeignKey("ElegiBien.Domain.Entities.SharedResult", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.Analysis", b =>
                {
                    b.Navigation("AirConditioningInput");

                    b.Navigation("AnalyticsEvents");

                    b.Navigation("ConsentRecords");

                    b.Navigation("DimensioningResult");

                    b.Navigation("ProductAlternatives");

                    b.Navigation("SharedResult");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ProductAlternative", b =>
                {
                    b.Navigation("ProductScore");
                });

            modelBuilder.Entity("ElegiBien.Domain.Entities.ProductScore", b =>
                {
                    b.Navigation("Factors");
                });
#pragma warning restore 612, 618
        }
    }
}
